volumes:
  pgdata:

services:
  db:
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE:-digitallions}
      PGDATA: /var/lib/postgresql/data/digitallions
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
    - postgres
  backend:
    container_name: backend
    hostname: backend
    image: "digitallionsbackend:latest"
    build:
      context: ./backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-digitallions}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_HOST: postgres
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}
    ports:
      - 8000:8000
      
  frontend:
    container_name: frontend
    image: "digitallionsfrontend:latest"
    build:
      context: ./frontend
    environment:
      API_URL: ${API_URL:-"http://localhost:8000"}
    ports:
      - 3000:3000
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "80:80"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
