"""Cascade on delete for all tablesa


Revision ID: 09d9cb9ceb8f
Revises: f21f685055bd
Create Date: 2024-08-05 18:38:47.262568

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09d9cb9ceb8f"
down_revision: str | None = "f21f685055bd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("attendances", "child_id",
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column("attendances", "workshop_id",
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint("attendances_workshop_id_fkey", "attendances", type_="foreignkey")
    op.drop_constraint("attendances_child_id_fkey", "attendances", type_="foreignkey")
    op.create_foreign_key(None, "attendances", "children", ["child_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key(None, "attendances", "workshops", ["workshop_id"], ["id"], ondelete="CASCADE")
    op.alter_column("children", "team_id",
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint("children_team_id_fkey", "children", type_="foreignkey")
    op.create_foreign_key(None, "children", "teams", ["team_id"], ["id"], ondelete="CASCADE")
    op.alter_column("teams", "community_id",
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint("teams_community_id_fkey", "teams", type_="foreignkey")
    op.create_foreign_key(None, "teams", "communities", ["community_id"], ["id"], ondelete="CASCADE")
    op.alter_column("workshops", "team_id",
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint("workshops_team_id_fkey", "workshops", type_="foreignkey")
    op.create_foreign_key(None, "workshops", "teams", ["team_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workshops", type_="foreignkey")
    op.create_foreign_key("workshops_team_id_fkey", "workshops", "teams", ["team_id"], ["id"])
    op.alter_column("workshops", "team_id",
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, "teams", type_="foreignkey")
    op.create_foreign_key("teams_community_id_fkey", "teams", "communities", ["community_id"], ["id"])
    op.alter_column("teams", "community_id",
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, "children", type_="foreignkey")
    op.create_foreign_key("children_team_id_fkey", "children", "teams", ["team_id"], ["id"])
    op.alter_column("children", "team_id",
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, "attendances", type_="foreignkey")
    op.drop_constraint(None, "attendances", type_="foreignkey")
    op.create_foreign_key("attendances_child_id_fkey", "attendances", "children", ["child_id"], ["id"])
    op.create_foreign_key("attendances_workshop_id_fkey", "attendances", "workshops", ["workshop_id"], ["id"])
    op.alter_column("attendances", "workshop_id",
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column("attendances", "child_id",
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
