"""Add community ID to team table

Revision ID: 279a9f1e7cc7
Revises: 336c0611be1f
Create Date: 2024-06-28 10:36:52.707868

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "279a9f1e7cc7"
down_revision: str | None = "336c0611be1f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("community_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "teams", "communities", ["community_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "teams", type_="foreignkey")
    op.drop_column("teams", "community_id")
    # ### end Alembic commands ###
