"""empty message

Revision ID: 27dcd3e4daf0
Revises: 5ae7d2fdf948
Create Date: 2024-07-08 22:01:44.520546

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "27dcd3e4daf0"
down_revision: str | None = "5ae7d2fdf948"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workshops", sa.Column("workshop_number", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workshops", "workshop_number")
    # ### end Alembic commands ###
