"""empty message

Revision ID: 5ae7d2fdf948
Revises: f0979b1a9eaa
Create Date: 2024-07-08 22:00:16.502765

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5ae7d2fdf948"
down_revision: str | None = "f0979b1a9eaa"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workshops", sa.Column("workshop_number", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("workshops", "workshop_number")
    # ### end Alembic commands ###
