"""Remove program tablre


Revision ID: ef8cd6011991
Revises: 27dcd3e4daf0
Create Date: 2024-07-19 13:10:29.800537

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ef8cd6011991"
down_revision: str | None = "27dcd3e4daf0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("programs")
    op.alter_column("workshops", "workshop_number",
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("workshops", "workshop_number",
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table("programs",
    sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column("program_id", sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column("workshop", sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column("workshop_name", sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint("id", name="programs_pkey")
    )
    # ### end Alembic commands ###
