"""Add is_registered flag to user col

Revision ID: 0f9912fc5973
Revises: abd3f0fa502b
Create Date: 2024-09-20 21:29:53.576772

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import expression

# revision identifiers, used by Alembic.
revision: str = "0f9912fc5973"
down_revision: str | None = "abd3f0fa502b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_registered",
            sa.Boolean(),
            server_default=expression.false(),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_registered")
    # ### end Alembic commands ###
