"""empty message

Revision ID: 168f2f4e6945
Revises: 97bed06b351a
Create Date: 2024-06-18 21:31:42.871951

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "168f2f4e6945"
down_revision: str | None = "97bed06b351a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teams",
        sa.Column("community_id", sa.Integer(), nullable=False, server_default="1"),
    )
    op.create_foreign_key(None, "teams", "communities", ["community_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "teams", type_="foreignkey")
    op.drop_column("teams", "community_id")
    # ### end Alembic commands ###
