"""empty message

Revision ID: 2593b5493005
Revises: 
Create Date: 2024-06-04 22:24:12.937335

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "2593b5493005"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
