"""Add children table

Revision ID: 2746d972cf2e
Revises: 6e52151007ed
Create Date: 2024-06-18 18:17:31.692887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '2746d972cf2e'
down_revision: Union[str, None] = '6e52151007ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('teams', sa.Column('community_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'teams', 'communities', ['community_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.drop_column('teams', 'community_id')
    op.drop_column('teams', 'name')
    # ### end Alembic commands ###
