"""Add teams-community relatino

Revision ID: 336c0611be1f
Revises: 860e69d5c304
Create Date: 2024-06-28 10:10:09.550787

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "336c0611be1f"
down_revision: str | None = "860e69d5c304"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("teams_community_id_fkey", "teams", type_="foreignkey")
    op.drop_column("teams", "community_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("community_id", sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key("teams_community_id_fkey", "teams", "communities", ["community_id"], ["id"])
    # ### end Alembic commands ###
