"""Remove col

Revision ID: 3d93f6a38942
Revises: 43d31a61becb
Create Date: 2024-07-30 22:49:36.017030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3d93f6a38942'
down_revision: Union[str, None] = '43d31a61becb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'program_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('program_tracker', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
