"""Remove programs table

Revision ID: 4c79ea1779c6
Revises: 3d93f6a38942
Create Date: 2024-07-30 22:52:33.821074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4c79ea1779c6'
down_revision: Union[str, None] = '3d93f6a38942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('programs')
    op.drop_column('teams', 'program_tracker')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('program_tracker', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_table('programs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('program_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workshop', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('workshop_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='programs_pkey')
    )
    # ### end Alembic commands ###
