"""empty message

Revision ID: 849e6031c717
Revises: 2746d972cf2e
Create Date: 2024-06-18 18:28:51.782947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '849e6031c717'
down_revision: Union[str, None] = '2746d972cf2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communities', 'is_active')
    op.drop_column('communities', 'created_at')
    op.drop_column('communities', 'name')
    op.drop_column('communities', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('communities', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('communities', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('communities', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
