"""empty message

Revision ID: 860e69d5c304
Revises: 
Create Date: 2024-06-25 17:44:25.847068

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "860e69d5c304"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("attendances",
    sa.Column("attendance", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("child_id", sa.Integer(), nullable=False),
    sa.Column("workshop_id", sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(["child_id"], ["children.id"], ),
    sa.ForeignKeyConstraint(["workshop_id"], ["workshops.id"], ),
    sa.PrimaryKeyConstraint("id")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("attendances")
    # ### end Alembic commands ###
