"""empty message

Revision ID: 97bed06b351a
Revises: a6c12150d823
Create Date: 2024-06-18 21:29:22.428848

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97bed06b351a"
down_revision: str | None = "a6c12150d823"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("teams", sa.Column("community_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "teams", "communities", ["community_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "teams", type_="foreignkey")
    op.drop_column("teams", "community_id")
    # ### end Alembic commands ###
