"""Remove null constraint pt 2


Revision ID: abd3f0fa502b
Revises: 8dadfc4c35a2
Create Date: 2024-09-16 15:37:24.482006

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abd3f0fa502b"
down_revision: str | None = "8dadfc4c35a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "first_name",
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column("users", "last_name",
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "last_name",
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column("users", "first_name",
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
