"""Set delete cascading

Revision ID: af56c0101e50
Revises: 033ac48b6ad3
Create Date: 2024-08-02 15:25:35.936326

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af56c0101e50"
down_revision: str | None = "033ac48b6ad3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("attendances", "workshop_id",
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint("attendances_workshop_id_fkey", "attendances", type_="foreignkey")
    op.create_foreign_key(None, "attendances", "workshops", ["workshop_id"], ["id"], ondelete="CASCADE")
    op.alter_column("teams", "community_id",
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint("teams_community_id_fkey", "teams", type_="foreignkey")
    op.create_foreign_key(None, "teams", "communities", ["community_id"], ["id"], ondelete="CASCADE")
    op.alter_column("workshops", "team_id",
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint("workshops_team_id_fkey", "workshops", type_="foreignkey")
    op.create_foreign_key(None, "workshops", "teams", ["team_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "workshops", type_="foreignkey")
    op.create_foreign_key("workshops_team_id_fkey", "workshops", "teams", ["team_id"], ["id"])
    op.alter_column("workshops", "team_id",
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, "teams", type_="foreignkey")
    op.create_foreign_key("teams_community_id_fkey", "teams", "communities", ["community_id"], ["id"])
    op.alter_column("teams", "community_id",
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, "attendances", type_="foreignkey")
    op.create_foreign_key("attendances_workshop_id_fkey", "attendances", "workshops", ["workshop_id"], ["id"])
    op.alter_column("attendances", "workshop_id",
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
