"""empty message

Revision ID: e26dddda784f
Revises: e9c8c615f44c
Create Date: 2024-06-19 16:58:46.296962

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e26dddda784f"
down_revision: str | None = "e9c8c615f44c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("children", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("children", "is_active")
    # ### end Alembic commands ###
