"""empty message

Revision ID: e2c5e1ae62d1
Revises: e26dddda784f
Create Date: 2024-06-19 16:59:59.152725

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e2c5e1ae62d1"
down_revision: str | None = "e26dddda784f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "children",
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=str(True)),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("children", "is_active")
    # ### end Alembic commands ###
