"""empty message

Revision ID: e4de94849ffe
Revises: b101c9f6da7f
Create Date: 2024-06-24 13:27:13.268365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4de94849ffe'
down_revision: Union[str, None] = 'b101c9f6da7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communities', sa.Column('last_updated_at', sa.DateTime(), nullable=False))
    op.drop_column('communities', 'updated_at')
    op.add_column('teams', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('teams', sa.Column('last_updated_at', sa.DateTime(), nullable=False))
    op.add_column('teams', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('last_updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_updated_at')
    op.drop_column('users', 'is_active')
    op.drop_column('teams', 'created_at')
    op.drop_column('teams', 'last_updated_at')
    op.drop_column('teams', 'is_active')
    op.add_column('communities', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('communities', 'last_updated_at')
    # ### end Alembic commands ###
