"""empty message

Revision ID: e9c8c615f44c
Revises: 953e4a87aee0
Create Date: 2024-06-19 09:14:24.192511

"""

from collections.abc import Sequence
from datetime import datetime

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e9c8c615f44c"
down_revision: str | None = "953e4a87aee0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "children",
        sa.Column(
            "last_updated_at",
            sa.DateTime(),
            nullable=False,
            server_default=str(datetime.now()),
        ),
    )
    op.drop_column("children", "last_edited")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "children",
        sa.Column(
            "last_edited",
            postgresql.TIMESTAMP(),
            autoincrement=False,
            nullable=False,
            server_default=str(datetime.now()),
        ),
    )
    op.drop_column("children", "last_updated_at")
    # ### end Alembic commands ###
