"""Add workshop col

Revision ID: f0979b1a9eaa
Revises: c999b3897e64
Create Date: 2024-07-08 21:58:38.389022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f0979b1a9eaa'
down_revision: Union[str, None] = 'c999b3897e64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workshops', sa.Column('workshop_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workshops', 'workshop_number')
    # ### end Alembic commands ###
