"""Set delete cascading v2

Revision ID: f906168ff9dd
Revises: af56c0101e50
Create Date: 2024-08-02 15:28:47.969482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f906168ff9dd'
down_revision: Union[str, None] = 'af56c0101e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('children', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('children_team_id_fkey', 'children', type_='foreignkey')
    op.create_foreign_key(None, 'children', 'teams', ['team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'children', type_='foreignkey')
    op.create_foreign_key('children_team_id_fkey', 'children', 'teams', ['team_id'], ['id'])
    op.alter_column('children', 'team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
