class ItemAlreadyExistsException(Exception): ...


class ItemNotFoundException(Exception): ...


class UserUnauthorizedException(Exception): ...


class CommunityNotFoundException(Exception): ...


class CommunityAlreadyExistsException(Exception): ...
