"""Custom exceptions for the app."""


class ChildNotFoundException(Exception): ...


class ChildHasAttendanceException(Exception): ...


class CommunityNotFoundException(Exception): ...


class CommunityAlreadyExistsException(Exception): ...


class ItemAlreadyExistsException(Exception): ...


class ItemNotFoundException(Exception): ...


class TeamHasChildrenException(Exception): ...


class TeamNotFoundException(Exception): ...


class UserUnauthorizedException(Exception): ...


class WorkshopNotFoundException(Exception): ...
