"""Custom exceptions for the app."""


class ChildAlreadyExistsException(Exception): ...


class ChildHasAttendanceException(Exception): ...


class ChildNotFoundException(Exception): ...


class ChildNotInTeam(Exception): ...


class CommunityNotFoundException(Exception): ...


class CommunityAlreadyExistsException(Exception): ...


class ItemAlreadyExistsException(Exception): ...


class ItemNotFoundException(Exception): ...


class TeamHasChildrenException(Exception): ...


class TeamNotFoundException(Exception): ...


class UserUnauthorizedException(Exception): ...


class WorkshopExistsException(Exception): ...


class WorkshopIncompleteAttendance(Exception): ...


class WorkshopNumberInvalidException(Exception): ...


class WorkshopNotFoundException(Exception): ...
